export const baseURL = 'https://hairsalonaa.000webhostapp.com/api';
export const signupURL = `${baseURL}/user/signup.php`
export const loginURL = `${baseURL}/user/login.php`
export const myProfileURL=`${baseURL}user/my_profile.php`
export const updateMeURL=`${baseURL}/user/update_me.php`
export const newProductURL = `${baseURL}/products/new_product.php`
export const updateProductURL = `${baseURL}/products/update_products.php`
export const deleteProductURL = `${baseURL}/products/delete_products.php`
export const productURL = `${baseURL}/products/products.php`
export const productIdURL = `${baseURL}/products/product_id`
export const uslugeURL = `${baseURL}/usluge/usluge.php`
export const newZahtevURL = `${baseURL}/zahtevi/novi_zahtev.php`
export const zahtevURL = `${baseURL}/zahtevi/zahtevi.php`
export const odobriZahtevURL = `${baseURL}/zahtevi/odobri_zahtev.php`
export const izbrisiZahtevURL = `${baseURL}/zahtevi/odbi_zahtev.php`
export const friseurURL = `${baseURL}/friseur/friseur.php`
export const newFriseurURL = `${baseURL}/friseur/new_friseur.php`
export const updateFriseurURL = `${baseURL}/friseur/update_friseur.php`
export const deleteFriseurURL = `${baseURL}/friseur/delete_friseur.php`
export const suppliersURL = `${baseURL}/supplier/suppliers.php`
export const newSupplierURL = `${baseURL}/supplier/new_supplier.php`
export const updateSupplierURL = `${baseURL}/supplier/update_supplier.php`
export const deleteSupplierURL = `${baseURL}/supplier/delete_supplier.php`
export const suppliesURL = `${baseURL}/supplies/supplies.php`
export const newSupplyURL = `${baseURL}/supplies/new_supply.php`
export const updateSupplyURL = `${baseURL}/supplies/update_supply.php`
export const deleteSupplyURL = `${baseURL}/supplies/delete_supply.php`
export const uslugeIdURL = `${baseURL}/usluge/usluge_id.php`
export const izmenaUslugeURL = `${baseURL}/usluge/izmeni_uslugu.php`
export const brisanjeUslugeURL = `${baseURL}/usluge/izbrisi_uslugu.php`
export const novaUslugaURL = `${baseURL}/usluge/nove_usluge.php`
export const makeOrderURL = `${baseURL}/porudzbine/make_order.php`
export const orderItemURL = `${baseURL}/porudzbine/newItem.php`
export const orderInfoURL = `${baseURL}/porudzbine/orderInfo.php`
export const myOrdersURL = `${baseURL}/porudzbine/my_orders.php`
export const deleteOrderURL = `${baseURL}/porudzbine/delete_order.php`
export const mojiZahteviURL=`${baseURL}/zahtevi/mojiZahtevi.php`
